apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vjcloudbank-api-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vijeshcloudops/vjcloudbank.git
    targetRevision: main
    path: manifests/charts/microservice
    helm:
      releaseName: api-gateway
      valueFiles:
        - ../../values/api-gateway-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vjcloudbank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
