apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sit-user-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vijeshcloudops/vjcloudbank.git
    targetRevision: main
    path: manifests/charts/microservice
    helm:
      releaseName: user-service
      valueFiles:
        - ../../values/user-service-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
