# ─────────────────────────────────────────────
# VjCloudBank — Account Service Deployment
# ─────────────────────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: vjcloudbank
  labels:
    app: account-service
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: 135808958462.dkr.ecr.ap-south-1.amazonaws.com/vjcloudbank/account-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: APP_ENV
              value: "production"
            - name: PORT
              value: "3002"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: JWT_SECRET
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /api/accounts/health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/accounts/health
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: vjcloudbank
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
